import {StyleSheet, Dimensions} from 'react-native';
import {COLORS, FONTS} from '../../constants';
const {height, width} = Dimensions.get('window');
export default StyleSheet.create({
  container: {
    backgroundColor: COLORS.white,
    flex: 1,
  },
  innercontainer: {
    width: width * 0.94,
    alignSelf: 'center',
    backgroundColor: COLORS.white,
    height: height,
  },
  addressbox: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    width: width * 0.93,
    marginVertical: height * 0.01,
    paddingHorizontal: height * 0.022,
    alignSelf: 'center',
    shadowColor: COLORS.black,
    elevation: 8,
    shadowOffset: {width: width * 0.15, height: 4},
    paddingTop: height * 0.01,
    paddingBottom: height * 0.02,
  },
  editbox: {
    alignSelf: 'flex-end',
    width: width * 0.2,
    height: height * 0.033,
    marginBottom: height * -0.015,
  },
  edit: {
    color: COLORS.primary,
    ...FONTS.fiveHundred,
    fontSize: width * 0.034,
    textAlign: 'right',
  },
  name: {
    color: COLORS.black,
    ...FONTS.fiveHundred,
    fontSize: width * 0.036,
    borderBottomWidth: 1,
    borderColor: COLORS.gray20,
    width: width * 0.76,
    alignSelf: 'center',
  },
  address: {
    color: COLORS.black,
    ...FONTS.fourHundred,
    fontSize: width * 0.032,
    borderBottomWidth: 1,
    borderColor: COLORS.gray20,
    width: width * 0.76,
    marginTop: height * 0.01,
    alignSelf: 'center',
  },
  cartrow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  change: {
    fontSize: width * 0.035,
    ...FONTS.fiveHundred,
    color: COLORS.primary,
    marginBottom: -2,
  },
  addheading: {
    fontSize: width * 0.038,
    ...FONTS.sixHundred,
    color: COLORS.black,
  },
  btnrow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 0.6,
    borderColor: COLORS.gray10,
    borderRadius: 60,
    marginVertical: height * 0.02,
    paddingHorizontal: width * 0.03,
    paddingVertical: width * 0.012,
    width: width * 0.94,
    alignSelf: 'center',
  },
  input: {
    fontSize: width * 0.034,
    ...FONTS.fiveHundred,
    width: width * 0.59,
    color: COLORS.black,
    marginBottom: -3,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: COLORS.gray20,
    paddingVertical: height * 0.012,
  },
  summry: {
    fontSize: width * 0.034,
    ...FONTS.fiveHundred,
    width: width * 0.7,
    color: COLORS.black,
  },
  price: {
    fontSize: width * 0.035,
    ...FONTS.sixHundred,
    color: COLORS.black,
  },
  usd: {
    fontSize: width * 0.03,
    ...FONTS.fiveHundred,
    color: COLORS.gray30,
  },
});
